import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const allergyMedicines: Medicine[] = [
  {
    id: "3",
    name: "Cetirizine",
    category: "cetirizine" as MedicineCategory,
    symptom: "alergi" as SymptomCategory,
    description: "Cetirizine adalah obat antihistamin yang digunakan untuk meredakan gejala alergi seperti rhinitis alergi dan urtikaria.",
    dosage: "Dewasa dan anak > 12 tahun: 1 tablet (10 mg) sekali sehari",
    active_ingredient: "Cetirizine HCl 10mg",
    side_effects: "Mengantuk, mulut kering, kelelahan",
    registration_number: "DTL2023111501",
    manufacturer: "Dexa Medica",
    activeIngredient: "Cetirizine HCl 10mg",
    sideEffects: "Mengantuk, mulut kering, kelelahan",
    bpomId: "DTL2023111501"
  },
  {
    id: "4",
    name: "Loratadine",
    category: "cetirizine1" as MedicineCategory,
    symptom: "alergi" as SymptomCategory,
    description: "Loratadine adalah antihistamin generasi kedua yang digunakan untuk meredakan gejala alergi seperti bersin, hidung berair, dan gatal-gatal.",
    dosage: "Dewasa dan anak > 6 tahun: 1 tablet (10 mg) sekali sehari",
    active_ingredient: "Loratadine 10mg",
    side_effects: "Sakit kepala, mulut kering, kelelahan",
    registration_number: "DTL2023111502",
    manufacturer: "Schering-Plough",
    activeIngredient: "Loratadine 10mg",
    sideEffects: "Sakit kepala, mulut kering, kelelahan",
    bpomId: "DTL2023111502"
  },
  {
    id: "48",
    name: "Cetirex",
    category: "cetirizine" as MedicineCategory,
    symptom: "alergi" as SymptomCategory,
    description: "Cetirex adalah obat antihistamin untuk meredakan gejala alergi seperti bersin, hidung berair, mata gatal.",
    dosage: "Dewasa: 1 tablet, 1 kali sehari",
    active_ingredient: "Cetirizine HCl 10mg",
    side_effects: "Mengantuk, mulut kering, kelelahan",
    registration_number: "DTL2023111531",
    manufacturer: "Pharos",
    registration_date: "2019-04-25",
    activeIngredient: "Cetirizine HCl 10mg",
    sideEffects: "Mengantuk, mulut kering, kelelahan",
    bpomId: "DTL2023111531",
    bpomRegistrationDate: "2019-04-25"
  },
  {
    id: "49",
    name: "Rhinos SR",
    category: "cetirizine1" as MedicineCategory,
    symptom: "alergi" as SymptomCategory,
    description: "Rhinos SR adalah obat antihistamin lepas lambat untuk meredakan gejala alergi dengan efek yang tahan lama.",
    dosage: "Dewasa: 1 kapsul, 1 kali sehari",
    active_ingredient: "Loratadine 10mg",
    side_effects: "Jarang menyebabkan mengantuk, mulut kering",
    registration_number: "DTL2023111532",
    manufacturer: "Dexa Medica",
    registration_date: "2020-07-14",
    activeIngredient: "Loratadine 10mg",
    sideEffects: "Jarang menyebabkan mengantuk, mulut kering",
    bpomId: "DTL2023111532",
    bpomRegistrationDate: "2020-07-14"
  },
  {
    id: "50",
    name: "Fexofenadine",
    category: "cetirizine2" as MedicineCategory,
    symptom: "alergi" as SymptomCategory,
    description: "Fexofenadine adalah antihistamin non-sedatif yang efektif meredakan gejala alergi tanpa menyebabkan kantuk.",
    dosage: "Dewasa: 1 tablet, 1-2 kali sehari",
    active_ingredient: "Fexofenadine HCl 120mg",
    side_effects: "Sakit kepala, mual, pusing",
    registration_number: "DTL2023111533",
    manufacturer: "Sanofi",
    registration_date: "2021-01-08",
    activeIngredient: "Fexofenadine HCl 120mg",
    sideEffects: "Sakit kepala, mual, pusing",
    bpomId: "DTL2023111533",
    bpomRegistrationDate: "2021-01-08"
  },
  {
    id: "51",
    name: "Claritin",
    category: "cetirizine" as MedicineCategory,
    symptom: "alergi" as SymptomCategory,
    description: "Claritin adalah antihistamin non-sedatif yang digunakan untuk meredakan gejala alergi musiman.",
    dosage: "Dewasa: 1 tablet, 1 kali sehari",
    active_ingredient: "Loratadine 10mg",
    side_effects: "Sakit kepala, mulut kering, kelelahan",
    registration_number: "DTL2023111534",
    manufacturer: "Schering-Plough",
    registration_date: "2019-09-20",
    activeIngredient: "Loratadine 10mg",
    sideEffects: "Sakit kepala, mulut kering, kelelahan",
    bpomId: "DTL2023111534",
    bpomRegistrationDate: "2019-09-20"
  }
];
