import { Medicine } from "../../types";

export const coughMedicines: Medicine[] = [
  {
    id: 3,
    name: "OBH Combi Plus",
    category: "obh",
    symptom: "batuk",
    description: "Obat batuk kombinasi dengan formula yang efektif untuk meredakan batuk berdahak dan gejala flu.",
    dosage: "Dewasa: 3x sehari 15ml, Anak 6-12 tahun: 3x sehari 10ml",
    activeIngredient: "Succus Liquiritiae, Ammonium Chloride, Chlorpheniramine maleate",
    sideEffects: "Mengantuk, mulut kering",
    bpomId: "BTL2023111501",
    manufacturer: "OBH Combi Indonesia"
  },
  {
    id: 6,
    name: "OBH Combi",
    category: "obh",
    symptom: "batuk",
    description: "OBH Combi adalah obat batuk kombinasi dari ekstrak tanaman dengan efek ekspektoran untuk melegakan batuk berdahak dan meredakan gejala flu.",
    dosage: "Dewasa: 3 sendok takar (15ml), 3 kali sehari. Anak 6-12 tahun: 2 sendok takar (10ml), 3 kali sehari.",
    activeIngredient: "Succus liquiritiae, Ammonium klorida, Efedrin HCl, Klorfeniramin maleat",
    sideEffects: "Mengantuk, mulut kering, gangguan pencernaan.",
    bpomId: "DTL9876543212A1",
  },
  {
    id: 7,
    name: "OBH Combi Anak",
    category: "obh",
    symptom: "batuk",
    description: "OBH Combi Anak diformulasikan khusus untuk anak-anak, dengan rasa yang lebih disukai dan dosis yang disesuaikan untuk mengatasi batuk berdahak pada anak.",
    dosage: "Anak 6-12 tahun: 2 sendok takar (10ml), 3 kali sehari. Anak 2-6 tahun: 1 sendok takar (5ml), 3 kali sehari.",
    activeIngredient: "Succus liquiritiae, Ammonium klorida, Efedrin HCl, Klorfeniramin maleat (kadar lebih rendah dari versi dewasa)",
    sideEffects: "Mengantuk, peningkatan aktivitas pada beberapa anak.",
    bpomId: "DTL9876543213A1",
  },
  {
    id: 8,
    name: "OBH Itrasal",
    category: "obh1",
    symptom: "batuk",
    description: "OBH Itrasal adalah obat batuk untuk mengatasi batuk berdahak, meredakan gejala bronkitis akut dan kronis, serta infeksi saluran pernapasan lainnya.",
    dosage: "Dewasa: 15 ml, 3 kali sehari. Anak 6-12 tahun: 10 ml, 3 kali sehari.",
    activeIngredient: "Succus liquiritiae, Ammonium klorida, Glycyrrhiza, Chlorpheniramine maleate",
    sideEffects: "Mengantuk, mulut kering, pusing.",
    bpomId: "DTL9876543214A1",
  },
  {
    id: 9,
    name: "OBH Tropica",
    category: "obh1",
    symptom: "batuk",
    description: "OBH Tropica adalah obat batuk herbal dengan formula tradisional yang dimodernisasi untuk mengatasi batuk berdahak.",
    dosage: "Dewasa: 15 ml, 3 kali sehari. Anak >6 tahun: 10 ml, 3 kali sehari.",
    activeIngredient: "Ekstrak akar manis, Ammonium klorida, Mentol",
    sideEffects: "Umumnya minimal, dapat mencakup gangguan pencernaan ringan.",
    bpomId: "DTL9876543215A1",
  },
  {
    id: 10,
    name: "Siladex Batuk & Flu",
    category: "obh2",
    symptom: "batuk",
    description: "Siladex Batuk & Flu adalah obat kombinasi untuk meredakan gejala batuk disertai flu seperti hidung tersumbat, bersin, dan demam.",
    dosage: "Dewasa: 15 ml, 3 kali sehari. Anak 6-12 tahun: 7.5 ml, 3 kali sehari.",
    activeIngredient: "Paracetamol, Dextromethorphan HBr, Chlorpheniramine maleate, Phenylephrine HCl",
    sideEffects: "Mengantuk, mulut kering, pusing, jantung berdebar.",
    bpomId: "DTL9876543216A1",
  },
  {
    id: 11,
    name: "Konidin",
    category: "obh2",
    symptom: "batuk",
    description: "Konidin adalah obat batuk yang mengandung dextromethorphan untuk meredakan batuk tidak berdahak akibat iritasi tenggorokan.",
    dosage: "Dewasa: 1 tablet, 3-4 kali sehari. Anak 6-12 tahun: 1/2 tablet, 3 kali sehari.",
    activeIngredient: "Dextromethorphan HBr 15mg",
    sideEffects: "Mengantuk, pusing, mual.",
    bpomId: "DTL9876543217A1",
  },
  {
    id: 11,
    name: "Woods Herbal",
    category: "obh",
    symptom: "batuk",
    description: "Woods Herbal adalah sirup batuk dengan formula herbal untuk meredakan batuk dan melegakan tenggorokan.",
    dosage: "Dewasa: 15ml, 3 kali sehari. Anak >6 tahun: 10ml, 3 kali sehari",
    activeIngredient: "Ekstrak Glycyrrhiza glabra, Peppermint oil",
    sideEffects: "Jarang terjadi, bisa menyebabkan mual ringan",
    bpomId: "TR2024111003",
    manufacturer: "Woods Pharmaceutical",
    storageCondition: "Simpan di tempat sejuk dan kering di bawah 30°C"
  },
  {
    id: 12,
    name: "Vicks Formula 44",
    category: "obh2",
    symptom: "batuk",
    description: "Vicks Formula 44 adalah obat batuk yang efektif untuk meredakan batuk kering dan mengurangi iritasi tenggorokan.",
    dosage: "Dewasa dan anak >12 tahun: 15ml setiap 6-8 jam",
    activeIngredient: "Dextromethorphan HBr 15mg/5ml",
    sideEffects: "Mengantuk, pusing, mulut kering",
    bpomId: "DTL2024111004",
    manufacturer: "Procter & Gamble",
    packaging: "Botol 100ml"
  },
];
