
import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const digestiveMedicines: Medicine[] = [
  {
    id: "62",
    name: "Promag",
    category: "antacid" as MedicineCategory,
    symptom: "pencernaan" as SymptomCategory,
    description: "Promag adalah obat antasida untuk meredakan gejala sakit maag, kembung, dan perut tidak nyaman.",
    dosage: "Dewasa: 1-2 tablet, 3 kali sehari",
    active_ingredient: "Hydrotalcite 200mg, Mg(OH)2 150mg, Simethicone 50mg",
    side_effects: "Konstipasi, diare ringan",
    registration_number: "DTL2023111545",
    manufacturer: "Kalbe Farma",
    registration_date: "2018-09-25",
    activeIngredient: "Hydrotalcite 200mg, Mg(OH)2 150mg, Simethicone 50mg",
    sideEffects: "Konstipasi, diare ringan",
    bpomId: "DTL2023111545",
    bpomRegistrationDate: "2018-09-25"
  },
  {
    id: "63",
    name: "Mylanta",
    category: "antacid" as MedicineCategory,
    symptom: "pencernaan" as SymptomCategory,
    description: "Mylanta adalah obat antasida untuk meredakan gejala sakit maag, kembung, dan mual.",
    dosage: "Dewasa: 1-2 sendok teh, 3-4 kali sehari",
    active_ingredient: "Aluminium Hydroxide, Magnesium Hydroxide, Simethicone",
    side_effects: "Konstipasi, diare ringan",
    registration_number: "DTL2023111546",
    manufacturer: "Johnson & Johnson",
    registration_date: "2019-03-14",
    activeIngredient: "Aluminium Hydroxide, Magnesium Hydroxide, Simethicone",
    sideEffects: "Konstipasi, diare ringan",
    bpomId: "DTL2023111546",
    bpomRegistrationDate: "2019-03-14"
  },
  {
    id: "64",
    name: "Diatabs",
    category: "antidiarrheal" as MedicineCategory,
    symptom: "pencernaan" as SymptomCategory,
    description: "Diatabs adalah obat antidiare untuk mengatasi diare tanpa komplikasi.",
    dosage: "Dewasa: 1 tablet setelah BAB cair, maksimal 8 tablet per hari",
    active_ingredient: "Loperamide HCl 2mg",
    side_effects: "Konstipasi, sakit perut, mulut kering",
    registration_number: "DTL2023111547",
    manufacturer: "United Laboratories",
    registration_date: "2020-05-18",
    activeIngredient: "Loperamide HCl 2mg",
    sideEffects: "Konstipasi, sakit perut, mulut kering",
    bpomId: "DTL2023111547",
    bpomRegistrationDate: "2020-05-18"
  },
  {
    id: "65",
    name: "Imodium",
    category: "antidiarrheal" as MedicineCategory,
    symptom: "pencernaan" as SymptomCategory,
    description: "Imodium adalah obat antidiare untuk mengatasi diare tanpa komplikasi.",
    dosage: "Dewasa: 2 kapsul awal, kemudian 1 kapsul setelah BAB cair, maksimal 8 kapsul per hari",
    active_ingredient: "Loperamide HCl 2mg",
    side_effects: "Konstipasi, sakit perut, mual",
    registration_number: "DTL2023111548",
    manufacturer: "Johnson & Johnson",
    registration_date: "2019-08-10",
    activeIngredient: "Loperamide HCl 2mg",
    sideEffects: "Konstipasi, sakit perut, mual",
    bpomId: "DTL2023111548",
    bpomRegistrationDate: "2019-08-10"
  },
  {
    id: "66",
    name: "Dulcolax",
    category: "laxative" as MedicineCategory,
    symptom: "pencernaan" as SymptomCategory,
    description: "Dulcolax adalah obat pencahar untuk mengatasi sembelit.",
    dosage: "Dewasa: 1-2 tablet diminum sebelum tidur",
    active_ingredient: "Bisacodyl 5mg",
    side_effects: "Kram perut, mual, diare",
    registration_number: "DTL2023111549",
    manufacturer: "Sanofi",
    registration_date: "2018-11-05",
    activeIngredient: "Bisacodyl 5mg",
    sideEffects: "Kram perut, mual, diare",
    bpomId: "DTL2023111549",
    bpomRegistrationDate: "2018-11-05"
  },
  {
    id: "67",
    name: "Microlax",
    category: "laxative" as MedicineCategory,
    symptom: "pencernaan" as SymptomCategory,
    description: "Microlax adalah enema pencahar untuk mengatasi sembelit dengan efek cepat.",
    dosage: "Dewasa: 1 tube, dimasukkan ke dalam rektum",
    active_ingredient: "Sodium Citrate, Sodium Lauryl Sulfoacetate, Sorbic Acid",
    side_effects: "Iritasi lokal, kram perut ringan",
    registration_number: "DTL2023111550",
    manufacturer: "Johnson & Johnson",
    registration_date: "2020-07-15",
    activeIngredient: "Sodium Citrate, Sodium Lauryl Sulfoacetate, Sorbic Acid",
    sideEffects: "Iritasi lokal, kram perut ringan",
    bpomId: "DTL2023111550",
    bpomRegistrationDate: "2020-07-15"
  }
];
