
import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const feverMedicines: Medicine[] = [
  {
    id: "52",
    name: "Sanmol",
    category: "paracetamol" as MedicineCategory,
    symptom: "demam" as SymptomCategory,
    description: "Sanmol adalah obat untuk menurunkan demam dan meredakan nyeri ringan hingga sedang.",
    dosage: "Dewasa: 1-2 tablet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg",
    side_effects: "Jarang terjadi reaksi alergi",
    registration_number: "DTL2023111535",
    manufacturer: "Sanbe Farma",
    registration_date: "2019-02-15",
    activeIngredient: "Paracetamol 500mg",
    sideEffects: "Jarang terjadi reaksi alergi",
    bpomId: "DTL2023111535",
    bpomRegistrationDate: "2019-02-15"
  },
  {
    id: "53",
    name: "Proris",
    category: "ibuprofen" as MedicineCategory,
    symptom: "demam" as SymptomCategory,
    description: "Proris adalah obat antiinflamasi non-steroid (NSAID) untuk menurunkan demam dan meredakan nyeri.",
    dosage: "Dewasa: 1 tablet, 3 kali sehari",
    active_ingredient: "Ibuprofen 400mg",
    side_effects: "Gangguan pencernaan, sakit kepala, pusing",
    registration_number: "DTL2023111536",
    manufacturer: "Soho",
    registration_date: "2020-06-18",
    activeIngredient: "Ibuprofen 400mg",
    sideEffects: "Gangguan pencernaan, sakit kepala, pusing",
    bpomId: "DTL2023111536",
    bpomRegistrationDate: "2020-06-18"
  },
  {
    id: "54",
    name: "Aspirin",
    category: "aspirin" as MedicineCategory,
    symptom: "demam" as SymptomCategory,
    description: "Aspirin adalah obat antiinflamasi yang digunakan untuk menurunkan demam dan meredakan nyeri.",
    dosage: "Dewasa: 1-2 tablet, 3-4 kali sehari",
    active_ingredient: "Acetylsalicylic Acid 500mg",
    side_effects: "Gangguan pencernaan, perdarahan lambung, reaksi alergi",
    registration_number: "DTL2023111537",
    manufacturer: "Bayer",
    registration_date: "2018-11-10",
    activeIngredient: "Acetylsalicylic Acid 500mg",
    sideEffects: "Gangguan pencernaan, perdarahan lambung, reaksi alergi",
    bpomId: "DTL2023111537",
    bpomRegistrationDate: "2018-11-10"
  },
  {
    id: "55",
    name: "Tempra",
    category: "paracetamol" as MedicineCategory,
    symptom: "demam" as SymptomCategory,
    description: "Tempra adalah obat untuk menurunkan demam pada anak-anak.",
    dosage: "Anak 6-12 tahun: 1 sendok takar, 3-4 kali sehari",
    active_ingredient: "Paracetamol 120mg/5ml",
    side_effects: "Jarang terjadi reaksi alergi",
    registration_number: "DTL2023111538",
    manufacturer: "Johnson & Johnson",
    registration_date: "2019-08-22",
    activeIngredient: "Paracetamol 120mg/5ml",
    sideEffects: "Jarang terjadi reaksi alergi",
    bpomId: "DTL2023111538",
    bpomRegistrationDate: "2019-08-22"
  },
  {
    id: "56",
    name: "Pamol",
    category: "paracetamol" as MedicineCategory,
    symptom: "demam" as SymptomCategory,
    description: "Pamol adalah obat untuk menurunkan demam dan meredakan nyeri ringan hingga sedang.",
    dosage: "Dewasa: 1-2 tablet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg",
    side_effects: "Jarang terjadi reaksi alergi",
    registration_number: "DTL2023111539",
    manufacturer: "Kimia Farma",
    registration_date: "2020-03-14",
    activeIngredient: "Paracetamol 500mg",
    sideEffects: "Jarang terjadi reaksi alergi",
    bpomId: "DTL2023111539",
    bpomRegistrationDate: "2020-03-14"
  }
];
