
import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const fluMedicines: Medicine[] = [
  {
    id: "7",
    name: "Decolgen",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Kombinasi untuk meredakan gejala flu seperti demam, hidung tersumbat, dan bersin.",
    dosage: "Dewasa: 1 tablet 3x sehari",
    active_ingredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    side_effects: "Mengantuk, mulut kering",
    registration_number: "DTL2023111505",
    manufacturer: "Darya-Varia",
    activeIngredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    sideEffects: "Mengantuk, mulut kering",
    bpomId: "DTL2023111505"
  },
  {
    id: "22",
    name: "Decolsin",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Decolsin adalah kombinasi dari beberapa bahan aktif untuk meredakan gejala flu seperti demam, sakit kepala, hidung tersumbat, dan bersin.",
    dosage: "Dewasa: 1 tablet setiap 8 jam.",
    active_ingredient: "Parasetamol 500mg, Fenilefrin HCl 10mg, Klorfeniramin maleat 2mg",
    side_effects: "Mengantuk, mulut kering, pusing, jantung berdebar.",
    registration_number: "DKL2023456783A1",
    manufacturer: "Darya-Varia Laboratoria",
    registration_date: "2018-11-12",
    activeIngredient: "Parasetamol 500mg, Fenilefrin HCl 10mg, Klorfeniramin maleat 2mg",
    sideEffects: "Mengantuk, mulut kering, pusing, jantung berdebar.",
    bpomId: "DKL2023456783A1",
    bpomRegistrationDate: "2018-11-12"
  },
  {
    id: "23",
    name: "Deconex",
    category: "decongestant" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Deconex mengandung pseudoefedrin sebagai dekongestan untuk melegakan hidung tersumbat akibat pilek atau sinusitis.",
    dosage: "Dewasa: 1 tablet setiap 12 jam.",
    active_ingredient: "Pseudoefedrin HCl 120mg",
    side_effects: "Insomnia, gelisah, mulut kering, peningkatan tekanan darah, jantung berdebar.",
    registration_number: "DKL2023456784A1",
    manufacturer: "Kalbe Farma",
    registration_date: "2019-06-24",
    activeIngredient: "Pseudoefedrin HCl 120mg",
    sideEffects: "Insomnia, gelisah, mulut kering, peningkatan tekanan darah, jantung berdebar.",
    bpomId: "DKL2023456784A1",
    bpomRegistrationDate: "2019-06-24"
  },
  {
    id: "24",
    name: "Alermin",
    category: "antihistamine" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Alermin mengandung klorfeniramin maleat untuk meredakan gejala alergi pada saluran pernapasan seperti bersin dan hidung berair.",
    dosage: "Dewasa: 1 tablet setiap 8 jam.",
    active_ingredient: "Klorfeniramin maleat 4mg",
    side_effects: "Mengantuk, pusing, mulut kering, gangguan penglihatan.",
    registration_number: "DKL2023456785A1",
    manufacturer: "Kimia Farma",
    registration_date: "2017-05-30",
    activeIngredient: "Klorfeniramin maleat 4mg",
    sideEffects: "Mengantuk, pusing, mulut kering, gangguan penglihatan.",
    bpomId: "DKL2023456785A1",
    bpomRegistrationDate: "2017-05-30"
  },
  {
    id: "15",
    name: "Coldact",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Coldact adalah obat kombinasi untuk meredakan gejala flu seperti demam, sakit kepala, hidung tersumbat, dan bersin-bersin.",
    dosage: "Dewasa: 1 kapsul setiap 8 jam.",
    active_ingredient: "Paracetamol, Phenylpropanolamine HCl, Chlorpheniramine maleate",
    side_effects: "Mengantuk, pusing, mulut kering",
    registration_number: "DTL2024111007",
    manufacturer: "Actavis Indonesia",
    packaging: "Strip 10 kapsul",
    activeIngredient: "Paracetamol, Phenylpropanolamine HCl, Chlorpheniramine maleate",
    sideEffects: "Mengantuk, pusing, mulut kering",
    bpomId: "DTL2024111007"
  },
  {
    id: "25",
    name: "Bodrex Flu & Batuk",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Kombinasi untuk meredakan gejala flu dan batuk seperti demam, sakit kepala, hidung tersumbat, dan batuk.",
    dosage: "Dewasa: 1 tablet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Dextromethorphan HBr 15mg",
    side_effects: "Mengantuk, jantung berdebar, mulut kering",
    registration_number: "DTL2023111508",
    manufacturer: "Tempo Scan Pacific",
    registration_date: "2019-08-15",
    activeIngredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Dextromethorphan HBr 15mg",
    sideEffects: "Mengantuk, jantung berdebar, mulut kering",
    bpomId: "DTL2023111508",
    bpomRegistrationDate: "2019-08-15"
  },
  {
    id: "26",
    name: "Mixagrip",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Untuk meredakan gejala flu seperti demam, sakit kepala, hidung tersumbat, dan bersin-bersin.",
    dosage: "Dewasa: 1 tablet, 3 kali sehari",
    active_ingredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    side_effects: "Mengantuk, mulut kering, pusing",
    registration_number: "DTL2023111509",
    manufacturer: "Kalbe Farma",
    registration_date: "2020-02-12",
    activeIngredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    sideEffects: "Mengantuk, mulut kering, pusing",
    bpomId: "DTL2023111509",
    bpomRegistrationDate: "2020-02-12"
  },
  {
    id: "27",
    name: "Ultraflu",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Obat kombinasi untuk meredakan gejala flu dan batuk dengan cepat.",
    dosage: "Dewasa: 1 kaplet, 3 kali sehari",
    active_ingredient: "Paracetamol 500mg, Guaifenesin 100mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    side_effects: "Mengantuk, mulut kering, jantung berdebar",
    registration_number: "DTL2023111510",
    manufacturer: "Darya-Varia",
    registration_date: "2019-11-30",
    activeIngredient: "Paracetamol 500mg, Guaifenesin 100mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    sideEffects: "Mengantuk, mulut kering, jantung berdebar",
    bpomId: "DTL2023111510",
    bpomRegistrationDate: "2019-11-30"
  },
  {
    id: "28",
    name: "Neozep Forte",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Obat kombinasi untuk meredakan gejala flu, demam, dan sakit kepala.",
    dosage: "Dewasa: 1 tablet, 3 kali sehari",
    active_ingredient: "Paracetamol 500mg, Phenylpropanolamine HCl 25mg, Chlorpheniramine maleate 2mg",
    side_effects: "Mengantuk, mulut kering, peningkatan tekanan darah",
    registration_number: "DTL2023111511",
    manufacturer: "United Laboratories",
    registration_date: "2018-06-18",
    activeIngredient: "Paracetamol 500mg, Phenylpropanolamine HCl 25mg, Chlorpheniramine maleate 2mg",
    sideEffects: "Mengantuk, mulut kering, peningkatan tekanan darah",
    bpomId: "DTL2023111511",
    bpomRegistrationDate: "2018-06-18"
  },
  {
    id: "29",
    name: "Actifed",
    category: "antihistamine" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Obat antihistamin dan dekongestan untuk meredakan gejala pilek, flu, dan alergi pada saluran pernapasan.",
    dosage: "Dewasa: 1 tablet, 3 kali sehari",
    active_ingredient: "Triprolidine HCl 2.5mg, Pseudoephedrine HCl 60mg",
    side_effects: "Mengantuk, mulut kering, gelisah, insomnia",
    registration_number: "DTL2023111512",
    manufacturer: "Johnson & Johnson",
    registration_date: "2019-03-25",
    activeIngredient: "Triprolidine HCl 2.5mg, Pseudoephedrine HCl 60mg",
    sideEffects: "Mengantuk, mulut kering, gelisah, insomnia",
    bpomId: "DTL2023111512",
    bpomRegistrationDate: "2019-03-25"
  },
  {
    id: "30",
    name: "OBH Combi Anak",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Obat batuk dan flu untuk anak dengan kombinasi ekspektoran dan antihistamin.",
    dosage: "Anak 6-12 tahun: 2 sendok teh, 3 kali sehari",
    active_ingredient: "Ammonium Chloride, Guaifenesin, Chlorpheniramine maleate",
    side_effects: "Mengantuk, mulut kering",
    registration_number: "DTL2023111513",
    manufacturer: "Combiphar",
    registration_date: "2020-09-14",
    activeIngredient: "Ammonium Chloride, Guaifenesin, Chlorpheniramine maleate",
    sideEffects: "Mengantuk, mulut kering",
    bpomId: "DTL2023111513",
    bpomRegistrationDate: "2020-09-14"
  },
  {
    id: "31",
    name: "Panadol Cold & Flu",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Obat untuk meredakan gejala flu, demam, dan sakit kepala.",
    dosage: "Dewasa: 1-2 kaplet, 4-6 jam sekali sesuai kebutuhan",
    active_ingredient: "Paracetamol 500mg, Phenylephrine HCl 5mg",
    side_effects: "Peningkatan tekanan darah, jantung berdebar",
    registration_number: "DTL2023111514",
    manufacturer: "GlaxoSmithKline",
    registration_date: "2019-05-17",
    activeIngredient: "Paracetamol 500mg, Phenylephrine HCl 5mg",
    sideEffects: "Peningkatan tekanan darah, jantung berdebar",
    bpomId: "DTL2023111514",
    bpomRegistrationDate: "2019-05-17"
  },
  {
    id: "32",
    name: "Siladex Cough & Cold",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Sirup batuk dan flu dengan kombinasi pereda batuk, ekspektoran, dan antihistamin.",
    dosage: "Dewasa: 3 sendok teh, 3 kali sehari",
    active_ingredient: "Dextromethorphan HBr, Guaifenesin, Chlorpheniramine maleate",
    side_effects: "Mengantuk, mulut kering, gangguan pencernaan",
    registration_number: "DTL2023111515",
    manufacturer: "Dexa Medica",
    registration_date: "2020-07-22",
    activeIngredient: "Dextromethorphan HBr, Guaifenesin, Chlorpheniramine maleate",
    sideEffects: "Mengantuk, mulut kering, gangguan pencernaan",
    bpomId: "DTL2023111515",
    bpomRegistrationDate: "2020-07-22"
  },
  {
    id: "33",
    name: "Triaminic Pilek",
    category: "antihistamine" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Sirup untuk meredakan gejala pilek pada anak seperti hidung tersumbat dan bersin.",
    dosage: "Anak 6-12 tahun: 2 sendok teh, 3 kali sehari",
    active_ingredient: "Chlorpheniramine maleate, Phenylephrine HCl",
    side_effects: "Mengantuk, peningkatan detak jantung",
    registration_number: "DTL2023111516",
    manufacturer: "Novartis",
    registration_date: "2019-10-03",
    activeIngredient: "Chlorpheniramine maleate, Phenylephrine HCl",
    sideEffects: "Mengantuk, peningkatan detak jantung",
    bpomId: "DTL2023111516",
    bpomRegistrationDate: "2019-10-03"
  },
  {
    id: "34",
    name: "Procold",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Obat untuk meredakan gejala flu, pilek, dan alergi.",
    dosage: "Dewasa: 1 kaplet, 3 kali sehari",
    active_ingredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    side_effects: "Mengantuk, mulut kering, pusing",
    registration_number: "DTL2023111517",
    manufacturer: "Phapros",
    registration_date: "2021-01-15",
    activeIngredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    sideEffects: "Mengantuk, mulut kering, pusing",
    bpomId: "DTL2023111517",
    bpomRegistrationDate: "2021-01-15"
  },
  {
    id: "35",
    name: "Vicks Formula 44",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Sirup batuk untuk meredakan batuk tidak berdahak dan iritasi tenggorokan.",
    dosage: "Dewasa: 2 sendok teh, 4 kali sehari",
    active_ingredient: "Dextromethorphan HBr, Chlorpheniramine maleate",
    side_effects: "Mengantuk, pusing, mulut kering",
    registration_number: "DTL2023111518",
    manufacturer: "Procter & Gamble",
    registration_date: "2018-08-30",
    activeIngredient: "Dextromethorphan HBr, Chlorpheniramine maleate",
    sideEffects: "Mengantuk, pusing, mulut kering",
    bpomId: "DTL2023111518",
    bpomRegistrationDate: "2018-08-30"
  },
  {
    id: "36",
    name: "Tremenza",
    category: "antihistamine" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Antihistamin untuk meredakan gejala alergi seperti bersin, hidung berair, dan mata gatal.",
    dosage: "Dewasa: 1 tablet, 2-3 kali sehari",
    active_ingredient: "Cetirizine HCl 10mg",
    side_effects: "Mengantuk, mulut kering, kelelahan",
    registration_number: "DTL2023111519",
    manufacturer: "Sanbe Farma",
    registration_date: "2020-04-12",
    activeIngredient: "Cetirizine HCl 10mg",
    sideEffects: "Mengantuk, mulut kering, kelelahan",
    bpomId: "DTL2023111519",
    bpomRegistrationDate: "2020-04-12"
  },
  {
    id: "37",
    name: "Flugesic",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Obat untuk meredakan gejala flu, demam, dan sakit kepala.",
    dosage: "Dewasa: 1 kaplet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg, Phenylephrine HCl 10mg",
    side_effects: "Peningkatan tekanan darah, jantung berdebar",
    registration_number: "DTL2023111520",
    manufacturer: "Kalbe Farma",
    registration_date: "2021-03-08",
    activeIngredient: "Paracetamol 500mg, Phenylephrine HCl 10mg",
    sideEffects: "Peningkatan tekanan darah, jantung berdebar",
    bpomId: "DTL2023111520",
    bpomRegistrationDate: "2021-03-08"
  }
];
