import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const fluMedicines: Medicine[] = [
  {
    id: "7",
    name: "Decolgen",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Kombinasi untuk meredakan gejala flu seperti demam, hidung tersumbat, dan bersin.",
    dosage: "Dewasa: 1 tablet 3x sehari",
    active_ingredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    side_effects: "Mengantuk, mulut kering",
    registration_number: "DTL2023111505",
    manufacturer: "Darya-Varia",
    activeIngredient: "Paracetamol 500mg, Phenylephrine HCl 10mg, Chlorpheniramine maleate 2mg",
    sideEffects: "Mengantuk, mulut kering",
    bpomId: "DTL2023111505"
  },
  {
    id: "22",
    name: "Decolsin",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Decolsin adalah kombinasi dari beberapa bahan aktif untuk meredakan gejala flu seperti demam, sakit kepala, hidung tersumbat, dan bersin.",
    dosage: "Dewasa: 1 tablet setiap 8 jam.",
    active_ingredient: "Parasetamol 500mg, Fenilefrin HCl 10mg, Klorfeniramin maleat 2mg",
    side_effects: "Mengantuk, mulut kering, pusing, jantung berdebar.",
    registration_number: "DKL2023456783A1",
    manufacturer: "Darya-Varia Laboratoria",
    registration_date: "2018-11-12",
    activeIngredient: "Parasetamol 500mg, Fenilefrin HCl 10mg, Klorfeniramin maleat 2mg",
    sideEffects: "Mengantuk, mulut kering, pusing, jantung berdebar.",
    bpomId: "DKL2023456783A1",
    bpomRegistrationDate: "2018-11-12"
  },
  {
    id: "23",
    name: "Deconex",
    category: "decongestant" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Deconex mengandung pseudoefedrin sebagai dekongestan untuk melegakan hidung tersumbat akibat pilek atau sinusitis.",
    dosage: "Dewasa: 1 tablet setiap 12 jam.",
    active_ingredient: "Pseudoefedrin HCl 120mg",
    side_effects: "Insomnia, gelisah, mulut kering, peningkatan tekanan darah, jantung berdebar.",
    registration_number: "DKL2023456784A1",
    manufacturer: "Kalbe Farma",
    registration_date: "2019-06-24",
    activeIngredient: "Pseudoefedrin HCl 120mg",
    sideEffects: "Insomnia, gelisah, mulut kering, peningkatan tekanan darah, jantung berdebar.",
    bpomId: "DKL2023456784A1",
    bpomRegistrationDate: "2019-06-24"
  },
  {
    id: "24",
    name: "Alermin",
    category: "antihistamine" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Alermin mengandung klorfeniramin maleat untuk meredakan gejala alergi pada saluran pernapasan seperti bersin dan hidung berair.",
    dosage: "Dewasa: 1 tablet setiap 8 jam.",
    active_ingredient: "Klorfeniramin maleat 4mg",
    side_effects: "Mengantuk, pusing, mulut kering, gangguan penglihatan.",
    registration_number: "DKL2023456785A1",
    manufacturer: "Kimia Farma",
    registration_date: "2017-05-30",
    activeIngredient: "Klorfeniramin maleat 4mg",
    sideEffects: "Mengantuk, pusing, mulut kering, gangguan penglihatan.",
    bpomId: "DKL2023456785A1",
    bpomRegistrationDate: "2017-05-30"
  },
  {
    id: "15",
    name: "Coldact",
    category: "combinationflu" as MedicineCategory,
    symptom: "flu_pilek" as SymptomCategory,
    description: "Coldact adalah obat kombinasi untuk meredakan gejala flu seperti demam, sakit kepala, hidung tersumbat, dan bersin-bersin.",
    dosage: "Dewasa: 1 kapsul setiap 8 jam.",
    active_ingredient: "Paracetamol, Phenylpropanolamine HCl, Chlorpheniramine maleate",
    side_effects: "Mengantuk, pusing, mulut kering",
    registration_number: "DTL2024111007",
    manufacturer: "Actavis Indonesia",
    packaging: "Strip 10 kapsul",
    activeIngredient: "Paracetamol, Phenylpropanolamine HCl, Chlorpheniramine maleate",
    sideEffects: "Mengantuk, pusing, mulut kering",
    bpomId: "DTL2024111007"
  }
];
