import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const headacheMedicines: Medicine[] = [
  {
    id: "1",
    name: "Panadol",
    category: "paracetamol" as MedicineCategory,
    symptom: "pusing" as SymptomCategory,
    description: "Panadol adalah obat yang mengandung paracetamol untuk meredakan nyeri ringan hingga sedang, seperti sakit kepala, sakit gigi, nyeri sendi, dan demam.",
    dosage: "Dewasa: 1-2 tablet 3-4 kali sehari sesuai kebutuhan. Jarak antar dosis minimal 4 jam, tidak lebih dari 8 tablet dalam 24 jam.",
    active_ingredient: "Paracetamol 500mg",
    side_effects: "Jarang terjadi reaksi alergi seperti ruam kulit.",
    registration_number: "DTL2023111500",
    manufacturer: "GlaxoSmithKline",
    activeIngredient: "Paracetamol 500mg",
    sideEffects: "Jarang terjadi reaksi alergi seperti ruam kulit.",
    bpomId: "DTL2023111500"
  },
  {
    id: "2",
    name: "Paracetamol",
    category: "paracetamol" as MedicineCategory,
    symptom: "pusing" as SymptomCategory,
    description: "Paracetamol adalah obat generik yang digunakan untuk meredakan demam dan nyeri ringan hingga sedang.",
    dosage: "Dewasa: 0.5 - 1 gram setiap 4-6 jam sesuai kebutuhan, hingga maksimum 4 gram sehari.",
    active_ingredient: "Paracetamol",
    side_effects: "Penggunaan jangka panjang atau dosis tinggi dapat menyebabkan kerusakan hati.",
    registration_number: "GTL2023100101A1",
    manufacturer: "Generic Manufacturer",
    activeIngredient: "Paracetamol",
    sideEffects: "Penggunaan jangka panjang atau dosis tinggi dapat menyebabkan kerusakan hati.",
    bpomId: "GTL2023100101A1"
  },
  {
    id: "38",
    name: "Bodrex",
    category: "bodrex" as MedicineCategory,
    symptom: "pusing" as SymptomCategory,
    description: "Bodrex adalah obat untuk meredakan sakit kepala dan demam dengan cepat.",
    dosage: "Dewasa: 1 tablet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg, Caffeine 50mg",
    side_effects: "Gelisah, jantung berdebar, insomnia",
    registration_number: "DTL2023111521",
    manufacturer: "Tempo Scan Pacific",
    registration_date: "2019-07-25",
    activeIngredient: "Paracetamol 500mg, Caffeine 50mg",
    sideEffects: "Gelisah, jantung berdebar, insomnia",
    bpomId: "DTL2023111521",
    bpomRegistrationDate: "2019-07-25"
  },
  {
    id: "39",
    name: "Paramex",
    category: "paracetamol" as MedicineCategory,
    symptom: "pusing" as SymptomCategory,
    description: "Paramex adalah obat analgesik dan antipiretik untuk meredakan sakit kepala dan demam.",
    dosage: "Dewasa: 1 tablet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg, Propyphenazone 150mg, Caffeine 50mg",
    side_effects: "Gangguan pencernaan, insomnia, jantung berdebar",
    registration_number: "DTL2023111522",
    manufacturer: "Konimex",
    registration_date: "2018-09-14",
    activeIngredient: "Paracetamol 500mg, Propyphenazone 150mg, Caffeine 50mg",
    sideEffects: "Gangguan pencernaan, insomnia, jantung berdebar",
    bpomId: "DTL2023111522",
    bpomRegistrationDate: "2018-09-14"
  },
  {
    id: "40",
    name: "Oskadon",
    category: "paracetamol" as MedicineCategory,
    symptom: "pusing" as SymptomCategory,
    description: "Oskadon adalah obat analgesik untuk meredakan sakit kepala, sakit gigi, dan nyeri otot.",
    dosage: "Dewasa: 1 tablet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg, Propyphenazone 150mg, Caffeine 50mg",
    side_effects: "Gangguan pencernaan, jantung berdebar, insomnia",
    registration_number: "DTL2023111523",
    manufacturer: "Sido Muncul",
    registration_date: "2020-03-18",
    activeIngredient: "Paracetamol 500mg, Propyphenazone 150mg, Caffeine 50mg",
    sideEffects: "Gangguan pencernaan, jantung berdebar, insomnia",
    bpomId: "DTL2023111523",
    bpomRegistrationDate: "2020-03-18"
  },
  {
    id: "41",
    name: "Panadol Extra",
    category: "panadol" as MedicineCategory,
    symptom: "pusing" as SymptomCategory,
    description: "Panadol Extra adalah obat untuk meredakan sakit kepala dan nyeri dengan cepat dan efektif.",
    dosage: "Dewasa: 1 tablet, 3-4 kali sehari",
    active_ingredient: "Paracetamol 500mg, Caffeine 65mg",
    side_effects: "Gelisah, jantung berdebar, insomnia",
    registration_number: "DTL2023111524",
    manufacturer: "GlaxoSmithKline",
    registration_date: "2019-11-05",
    activeIngredient: "Paracetamol 500mg, Caffeine 65mg",
    sideEffects: "Gelisah, jantung berdebar, insomnia",
    bpomId: "DTL2023111524",
    bpomRegistrationDate: "2019-11-05"
  },
  {
    id: "42",
    name: "Tolak Angin",
    category: "herbal" as MedicineCategory,
    symptom: "pusing" as SymptomCategory,
    description: "Tolak Angin adalah obat herbal untuk meredakan gejala masuk angin seperti pusing, mual, dan perut kembung.",
    dosage: "Dewasa: 1 sachet, 3 kali sehari",
    active_ingredient: "Ekstrak Zingiber officinale (Jahe), Mentha arvensis (Mint), dan ramuan herbal lainnya",
    side_effects: "Jarang terjadi reaksi alergi",
    registration_number: "DTL2023111525",
    manufacturer: "Sidomuncul",
    registration_date: "2018-10-17",
    activeIngredient: "Ekstrak Zingiber officinale (Jahe), Mentha arvensis (Mint), dan ramuan herbal lainnya",
    sideEffects: "Jarang terjadi reaksi alergi",
    bpomId: "DTL2023111525",
    bpomRegistrationDate: "2018-10-17"
  }
];
