
import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const painMedicines: Medicine[] = [
  {
    id: "57",
    name: "Ponstan",
    category: "asam_mefenamat" as MedicineCategory,
    symptom: "nyeri" as SymptomCategory,
    description: "Ponstan adalah obat antiinflamasi non-steroid untuk meredakan nyeri ringan hingga sedang, termasuk nyeri haid.",
    dosage: "Dewasa: 1 kapsul, 3 kali sehari",
    active_ingredient: "Asam Mefenamat 500mg",
    side_effects: "Gangguan pencernaan, mual, pusing",
    registration_number: "DTL2023111540",
    manufacturer: "Pfizer",
    registration_date: "2019-05-20",
    activeIngredient: "Asam Mefenamat 500mg",
    sideEffects: "Gangguan pencernaan, mual, pusing",
    bpomId: "DTL2023111540",
    bpomRegistrationDate: "2019-05-20"
  },
  {
    id: "58",
    name: "Mefinal",
    category: "asam_mefenamat" as MedicineCategory,
    symptom: "nyeri" as SymptomCategory,
    description: "Mefinal adalah obat antiinflamasi untuk meredakan nyeri ringan hingga sedang dan nyeri haid.",
    dosage: "Dewasa: 1 kaplet, 3 kali sehari",
    active_ingredient: "Asam Mefenamat 500mg",
    side_effects: "Gangguan pencernaan, mual, diare",
    registration_number: "DTL2023111541",
    manufacturer: "Sanbe Farma",
    registration_date: "2020-02-18",
    activeIngredient: "Asam Mefenamat 500mg",
    sideEffects: "Gangguan pencernaan, mual, diare",
    bpomId: "DTL2023111541",
    bpomRegistrationDate: "2020-02-18"
  },
  {
    id: "59",
    name: "Ketopain",
    category: "dexketoprofen" as MedicineCategory,
    symptom: "nyeri" as SymptomCategory,
    description: "Ketopain adalah obat analgesik kuat untuk meredakan nyeri sedang hingga berat.",
    dosage: "Dewasa: 1 tablet, 3 kali sehari",
    active_ingredient: "Dexketoprofen 25mg",
    side_effects: "Gangguan pencernaan, mual, muntah, sakit kepala",
    registration_number: "DTL2023111542",
    manufacturer: "Dexa Medica",
    registration_date: "2021-01-12",
    activeIngredient: "Dexketoprofen 25mg",
    sideEffects: "Gangguan pencernaan, mual, muntah, sakit kepala",
    bpomId: "DTL2023111542",
    bpomRegistrationDate: "2021-01-12"
  },
  {
    id: "60",
    name: "Voltaren",
    category: "dexketoprofen" as MedicineCategory,
    symptom: "nyeri" as SymptomCategory,
    description: "Voltaren adalah obat antiinflamasi non-steroid untuk meredakan nyeri dan peradangan pada otot dan sendi.",
    dosage: "Dewasa: 1 tablet, 2-3 kali sehari",
    active_ingredient: "Diclofenac Sodium 50mg",
    side_effects: "Gangguan pencernaan, sakit kepala, pusing",
    registration_number: "DTL2023111543",
    manufacturer: "Novartis",
    registration_date: "2019-07-15",
    activeIngredient: "Diclofenac Sodium 50mg",
    sideEffects: "Gangguan pencernaan, sakit kepala, pusing",
    bpomId: "DTL2023111543",
    bpomRegistrationDate: "2019-07-15"
  },
  {
    id: "61",
    name: "Kaltrofen",
    category: "dexketoprofen" as MedicineCategory,
    symptom: "nyeri" as SymptomCategory,
    description: "Kaltrofen adalah obat antiinflamasi untuk meredakan nyeri dan peradangan pada otot dan sendi.",
    dosage: "Dewasa: 1 tablet, 3 kali sehari",
    active_ingredient: "Dexketoprofen 25mg",
    side_effects: "Gangguan pencernaan, mual, pusing",
    registration_number: "DTL2023111544",
    manufacturer: "Kalbe Farma",
    registration_date: "2020-04-10",
    activeIngredient: "Dexketoprofen 25mg",
    sideEffects: "Gangguan pencernaan, mual, pusing",
    bpomId: "DTL2023111544",
    bpomRegistrationDate: "2020-04-10"
  }
];
