
import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const vitaminSupplements: Medicine[] = [
  {
    id: "301",
    name: "Redoxon Double Action",
    category: "vitamin_c" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen vitamin C dan zinc untuk meningkatkan daya tahan tubuh dan menjaga kesehatan.",
    dosage: "Dewasa: 1 tablet effervescent dilarutkan dalam segelas air, diminum 1 kali sehari.",
    active_ingredient: "Vitamin C 1000mg, Zinc 10mg",
    side_effects: "Pada dosis tinggi dapat menyebabkan gangguan pencernaan ringan.",
    registration_number: "SD2023789001",
    manufacturer: "Bayer Indonesia",
    registration_date: "2020-06-08",
    storage_condition: "Simpan pada suhu ruangan di tempat kering",
    activeIngredient: "Vitamin C 1000mg, Zinc 10mg",
    sideEffects: "Pada dosis tinggi dapat menyebabkan gangguan pencernaan ringan.",
    bpomId: "SD2023789001",
    bpomRegistrationDate: "2020-06-08"
  },
  {
    id: "302",
    name: "Enervon-C",
    category: "multivitamin" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen multivitamin mengandung vitamin B kompleks dan vitamin C untuk menjaga stamina dan kesehatan tubuh.",
    dosage: "Dewasa: 1 tablet, 1-2 kali sehari.",
    active_ingredient: "Vitamin B1 50mg, B2 25mg, B6 10mg, B12 5mcg, Vitamin C 500mg",
    side_effects: "Jarang terjadi, dapat menyebabkan urin berwarna kuning terang.",
    registration_number: "SD2023789002",
    manufacturer: "Medifarma Laboratories",
    registration_date: "2019-11-20",
    storage_condition: "Simpan pada suhu di bawah 30°C, di tempat kering dan terhindar dari sinar matahari langsung",
    activeIngredient: "Vitamin B1 50mg, B2 25mg, B6 10mg, B12 5mcg, Vitamin C 500mg",
    sideEffects: "Jarang terjadi, dapat menyebabkan urin berwarna kuning terang.",
    bpomId: "SD2023789002",
    bpomRegistrationDate: "2019-11-20"
  },
  {
    id: "303",
    name: "Calcimex D",
    category: "mineral" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen kalsium dan vitamin D untuk menjaga kesehatan tulang dan mencegah osteoporosis.",
    dosage: "Dewasa: 1 tablet, 1-2 kali sehari setelah makan.",
    active_ingredient: "Calcium Carbonate 500mg, Vitamin D3 200 IU",
    side_effects: "Konstipasi, kembung, mual ringan.",
    registration_number: "SD2023789003",
    manufacturer: "Kalbe Farma",
    registration_date: "2020-04-15",
    storage_condition: "Simpan pada suhu ruangan yang kering",
    activeIngredient: "Calcium Carbonate 500mg, Vitamin D3 200 IU",
    sideEffects: "Konstipasi, kembung, mual ringan.",
    bpomId: "SD2023789003",
    bpomRegistrationDate: "2020-04-15"
  },
  {
    id: "304",
    name: "Sangobion",
    category: "mineral" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen zat besi untuk mencegah dan mengatasi anemia defisiensi besi.",
    dosage: "Dewasa: 1 kapsul, 1-2 kali sehari setelah makan.",
    active_ingredient: "Ferrous Gluconate 250mg, Vitamin B12 7.5mcg, Folic Acid 1mg, Vitamin C 50mg",
    side_effects: "Perubahan warna tinja menjadi hitam, konstipasi, mual.",
    registration_number: "SD2023789004",
    manufacturer: "Merck Indonesia",
    registration_date: "2019-09-12",
    storage_condition: "Simpan pada suhu di bawah 30°C",
    activeIngredient: "Ferrous Gluconate 250mg, Vitamin B12 7.5mcg, Folic Acid 1mg, Vitamin C 50mg",
    sideEffects: "Perubahan warna tinja menjadi hitam, konstipasi, mual.",
    bpomId: "SD2023789004",
    bpomRegistrationDate: "2019-09-12"
  },
  {
    id: "305",
    name: "Combantrin",
    category: "herbal_supplement" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen herbal untuk mengatasi infeksi cacing pada saluran pencernaan.",
    dosage: "Dewasa dan anak >2 tahun: Dosis berdasarkan berat badan, biasanya 1 tablet untuk setiap 10kg berat badan, diberikan sebagai dosis tunggal.",
    active_ingredient: "Pyrantel Pamoate 125mg",
    side_effects: "Sakit perut ringan, mual, muntah, diare, pusing.",
    registration_number: "DTL2023789005",
    manufacturer: "Pfizer Indonesia",
    registration_date: "2018-11-05",
    storage_condition: "Simpan pada suhu ruangan yang kering",
    activeIngredient: "Pyrantel Pamoate 125mg",
    sideEffects: "Sakit perut ringan, mual, muntah, diare, pusing.",
    bpomId: "DTL2023789005",
    bpomRegistrationDate: "2018-11-05"
  }
];
