
import { Medicine, MedicineCategory, SymptomCategory } from "../../types";

export const vitaminMedicines: Medicine[] = [
  {
    id: "301",
    name: "Enervon-C",
    category: "vitamin_c" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen vitamin C dan B kompleks untuk meningkatkan daya tahan tubuh dan mengurangi kelelahan.",
    dosage: "Dewasa: 1 tablet sehari",
    active_ingredient: "Vitamin C 500mg, Vitamin B1, B2, B6, B12, Nicotinamide, Calcium Pantothenate",
    side_effects: "Mual, gangguan pencernaan pada dosis tinggi",
    registration_number: "SD2023789001",
    manufacturer: "Medifarma",
    registration_date: "2020-03-15",
    activeIngredient: "Vitamin C 500mg, Vitamin B1, B2, B6, B12, Nicotinamide, Calcium Pantothenate",
    sideEffects: "Mual, gangguan pencernaan pada dosis tinggi",
    bpomId: "SD2023789001",
    bpomRegistrationDate: "2020-03-15"
  },
  {
    id: "302",
    name: "Blackmores Multivitamin",
    category: "multivitamin" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen multivitamin dan mineral untuk mendukung kesehatan secara menyeluruh dan meningkatkan daya tahan tubuh.",
    dosage: "Dewasa: 1 tablet sehari dengan makanan",
    active_ingredient: "Vitamin A, B1, B2, B3, B5, B6, B12, C, D, E, Zat Besi, Kalsium, Magnesium, Zinc",
    side_effects: "Mual ringan jika diminum tanpa makanan",
    registration_number: "SD2023789002",
    manufacturer: "Blackmores",
    registration_date: "2021-01-10",
    activeIngredient: "Vitamin A, B1, B2, B3, B5, B6, B12, C, D, E, Zat Besi, Kalsium, Magnesium, Zinc",
    sideEffects: "Mual ringan jika diminum tanpa makanan",
    bpomId: "SD2023789002",
    bpomRegistrationDate: "2021-01-10"
  },
  {
    id: "303",
    name: "CDR Fortos",
    category: "mineral" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen kalsium effervescent untuk meningkatkan kepadatan tulang dan mencegah osteoporosis.",
    dosage: "Dewasa: 1 tablet larut dalam air, diminum 1 kali sehari",
    active_ingredient: "Calcium 500mg, Vitamin D3 200 IU",
    side_effects: "Konstipasi, kembung, mual",
    registration_number: "SD2023789003",
    manufacturer: "Bayer",
    registration_date: "2019-11-05",
    activeIngredient: "Calcium 500mg, Vitamin D3 200 IU",
    sideEffects: "Konstipasi, kembung, mual",
    bpomId: "SD2023789003",
    bpomRegistrationDate: "2019-11-05"
  },
  {
    id: "304",
    name: "Sangobion",
    category: "mineral" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen zat besi untuk mencegah dan mengatasi anemia defisiensi besi.",
    dosage: "Dewasa: 1 kapsul, 1-2 kali sehari",
    active_ingredient: "Ferrous Gluconate 250mg, Vitamin C, B12, Folic Acid",
    side_effects: "Konstipasi, kotoran berwarna hitam, mual",
    registration_number: "SD2023789004",
    manufacturer: "Merck",
    registration_date: "2020-05-18",
    activeIngredient: "Ferrous Gluconate 250mg, Vitamin C, B12, Folic Acid",
    sideEffects: "Konstipasi, kotoran berwarna hitam, mual",
    bpomId: "SD2023789004",
    bpomRegistrationDate: "2020-05-18"
  },
  {
    id: "305",
    name: "Fatigon Spirit",
    category: "multivitamin" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen multivitamin untuk mengatasi kelelahan dan meningkatkan stamina.",
    dosage: "Dewasa: 1 kaplet, 1-2 kali sehari",
    active_ingredient: "Royal Jelly, Ginseng, Vitamin B1, B6, B12",
    side_effects: "Jarang terjadi reaksi alergi",
    registration_number: "SD2023789005",
    manufacturer: "Kalbe Farma",
    registration_date: "2019-08-24",
    activeIngredient: "Royal Jelly, Ginseng, Vitamin B1, B6, B12",
    sideEffects: "Jarang terjadi reaksi alergi",
    bpomId: "SD2023789005",
    bpomRegistrationDate: "2019-08-24"
  },
  {
    id: "306",
    name: "Hemaviton",
    category: "multivitamin" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen multivitamin untuk meningkatkan stamina dan mengurangi kelelahan.",
    dosage: "Dewasa: 1 tablet, 1-2 kali sehari",
    active_ingredient: "Royal Jelly, Ginseng, Vitamin B1, B6, B12, C",
    side_effects: "Insomnia jika diminum terlalu sore atau malam",
    registration_number: "SD2023789006",
    manufacturer: "Tempo Scan Pacific",
    registration_date: "2020-02-12",
    activeIngredient: "Royal Jelly, Ginseng, Vitamin B1, B6, B12, C",
    sideEffects: "Insomnia jika diminum terlalu sore atau malam",
    bpomId: "SD2023789006",
    bpomRegistrationDate: "2020-02-12"
  },
  {
    id: "307",
    name: "Tolak Angin Herbal",
    category: "herbal_supplement" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen herbal untuk meningkatkan daya tahan tubuh dan mengatasi gejala masuk angin.",
    dosage: "Dewasa: 1 sachet, 1-3 kali sehari",
    active_ingredient: "Ekstrak Zingiber officinale (Jahe), Mentha arvensis (Mint), Amomum compactum (Kapulaga)",
    side_effects: "Sensasi hangat di tenggorokan",
    registration_number: "SD2023789007",
    manufacturer: "Sidomuncul",
    registration_date: "2019-06-15",
    activeIngredient: "Ekstrak Zingiber officinale (Jahe), Mentha arvensis (Mint), Amomum compactum (Kapulaga)",
    sideEffects: "Sensasi hangat di tenggorokan",
    bpomId: "SD2023789007",
    bpomRegistrationDate: "2019-06-15"
  },
  {
    id: "308",
    name: "Curcuma Plus",
    category: "herbal_supplement" as MedicineCategory,
    symptom: "vitamin_suplemen" as SymptomCategory,
    description: "Suplemen herbal dengan ekstrak kunyit dan vitamin untuk meningkatkan nafsu makan dan daya tahan tubuh anak.",
    dosage: "Anak 6-12 tahun: 1 sendok makan, 1-2 kali sehari",
    active_ingredient: "Ekstrak Curcuma longa (Kunyit), Vitamin A, C, E, Zink",
    side_effects: "Jarang terjadi reaksi alergi",
    registration_number: "SD2023789008",
    manufacturer: "Kalbe Farma",
    registration_date: "2020-09-10",
    activeIngredient: "Ekstrak Curcuma longa (Kunyit), Vitamin A, C, E, Zink",
    sideEffects: "Jarang terjadi reaksi alergi",
    bpomId: "SD2023789008",
    bpomRegistrationDate: "2020-09-10"
  }
];
