// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://harttqsomtrfyzsgboxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhcnR0cXNvbXRyZnl6c2dib3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTA2MDUsImV4cCI6MjA2MDUyNjYwNX0.qikTudhb0jM6emhQcObvg3fX4KZshyW-DuLVsXbv608";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);